# -*- coding: utf-8 -*-
"""APEX_PLANET_TASK_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vlRr_ei6CG5RvOEls_PF8SENvAl57ldI
"""

import pandas as pd

df = pd.read_csv("netflix_titles.csv")
print(df.head())
df.info()

# Remove duplicates
df = df.drop_duplicates()

# Fill missing values
df['director'] = df['director'].fillna('Unknown')
df['cast'] = df['cast'].fillna('Not Available')
df['country'] = df['country'].fillna('Unknown')

# Convert date
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')

# Feature engineering
df['year_added'] = df['date_added'].dt.year

# Clean column names
df.columns = df.columns.str.lower().str.replace(' ', '_')

df.to_csv("cleaned_netflix_data.csv", index=False)